#!/usr/bin/env node
let painted = 0;
const paint = (why) => process.stdout.write(`\r\n[repaint ${++painted}: ${why}]`);

process.stdout.write('\x1b[?1004h');
process.stdout.on('resize', () => paint('winch'));

if (process.stdin.isTTY) process.stdin.setRawMode(true);
const housekeeping = () => process.stdout.write('\x1b(B\x0f\x1b[?1000h\x1b[?1002h\x1b[?1003h\x1b[?1006h');

process.stdin.on('data', (data) => {
  const seen = data.toString();
  if (seen.includes('\x1b[I')) paint('focus in');
  else if (seen.includes('\x1b[O')) paint('focus out');
  else if (seen.includes('q')) housekeeping();
  else if (seen.includes('t')) process.stdout.write('\x1b]0;renamed-itself\x07');
  else paint('typed');
});

paint('start');
setInterval(() => {}, 1 << 30);
